# Command Blocks For Everyone. Minecraft Mod.
# Copyright (C) 2020 mooviies
# https://github.com/mooviies/CommandBlocksForEveryone
#
# This work is licensed under the Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License.
# To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-sa/4.0/.
modLoader="javafml"
loaderVersion="[31,)"
[[mods]]
modId="cbforeveryone"
version="${file.jarVersion}"
displayName="Command Blocks For Everyone"
authors="mooviies"
description='''
Command Blocks For Everyone. Minecraft Mod.
Copyright (C) 2020 mooviies
https://github.com/mooviies/CommandBlocksForEveryone

This mod gives the ability to edit command blocks to non creative players.
Permissions can be set globally or on a player basis.

This work is licensed under the Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License.
To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-sa/4.0/.
'''